name: backport
on:
  pull_request_target:
    types: [closed, labeled]

permissions: {}

jobs:
  backport:
    permissions:
      contents: write
      pull-requests: write
    name: Backport Pull Request
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true

      # - uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
      #   id: app-token
      #   with:
      #     app-id: ${{ vars.BACKPORT_APP }}
      #     private-key: ${{ secrets.BACKPORT_KEY }}

      - name: Create backport PR
        id: backport
        uses: korthout/backport-action@3c06f323a58619da1e8522229ebc8d5de2633e46 # v4.3.0
        with:
          pull_title: "${pull_title}"
          label_pattern: "^release:backport ([^ ]+)$"
          auto_merge_enabled: true
          auto_merge_method: squash
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create failed backport label
        if: ${{ steps.backport.outputs.was_successful == 'false' }}
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs:backport']
            })
