name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
      - uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: ${{ steps.release.outputs.release_created }}
        with:
          persist-credentials: true
          token: ${{ steps.app-token.outputs.token }}

      - uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
      - name: Create release branch
        shell: bash
        if: ${{ steps.release.outputs.release_created }}
        env:
          BRANCH: v${{ steps.release.outputs.major }}.${{  steps.release.outputs.minor }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git checkout -b "$BRANCH"
          git push -u origin "$BRANCH"

      - name: Create backport label
        shell: bash
        if: ${{ steps.release.outputs.release_created }}
        env:
          LABEL: v${{ steps.release.outputs.major }}.${{  steps.release.outputs.minor }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh label create "release:backport $LABEL"
